### ISSUE TITLE
Firefox Nightly no longer publishing signed checksums (checksums.asc)

### ISSUE THREAD

**Issue by panchaea** [mozilla/nixpkgs-mozilla#199] opened 2019-08-18 08:22 UTC
It seems that `*.checksums.asc` files are [no longer being included](https://bugzilla.mozilla.org/show_bug.cgi?id=1567429) in nightly releases. This makes it impossible to build releases after  `2019-08-16-09-48-15` using this overlay.

I've pinned the last working release in the meantime:

```
  firefoxNightlyPinned = super.lib.firefoxOverlay.firefoxVersion {
    name = "Firefox Nightly";
    version = "70.0a1";
    # Later builds no longer include signed checksums, which breaks the overlay
    timestamp = "2019-08-15-19-35-05"; 
    release = false;
  };
```

From the linked issue, it seems like the plan is to move checksum signing to another part of the release pipeline - does this mean these files are expected to make a return at some point, or does the overlay need a patch?

**Comment by rail** [comment] 2019-08-19 00:37
I don't think the per-file signatures are coming back. @MihaiTabara may have more information about where we can get the signatures of the files. I think the overlay will need a patch in any case.

**Comment by nbp** [comment] 2019-08-22 09:58
It seems to only generate signature files for `*.tar.bz2` file, which sounds like a regression for all other files.

**Comment by nbp** [comment] 2019-08-27 16:12
Discussing with @JohanLorenzo , the problem is that we should at least have a big-fat checksum file and its signature for the content of the nightly.

In the mean time, you can disable the checksum verification by commenting the following lines:
https://github.com/mozilla/nixpkgs-mozilla/blob/master/firefox-overlay.nix#L107-L109

Once the big-fat checksum file comes back with an associated signature, we should update the URL for downloading nightly versions:
https://github.com/mozilla/nixpkgs-mozilla/blob/master/firefox-overlay.nix#L62-L75

**Comment by MihaiTabara** [comment] 2019-09-02 13:33
Sorry for the bustage while I was out on PTO. The plan indeed is to make nightlies look more like releases, hence backport the big-fat checksums along with their signatures. That work is coming by EOQ3 so hopefully this temporarily pin will be short lived. I've added a todo to myself to comment to this issue once that support lands.

**Comment by nbp** [comment] 2019-10-16 12:09
@MihaiTabara Any plan to get this issue fixed on Firefox server side?

**Comment by arilotter** [comment] 2019-12-05 16:08
@MihaiTabara Did you get a chance to take another look at this issue?
The last Firefox version that you can install through this derivation is `2019-08-15-19-35-05`, which is now 3.5 months out of date. I'd open a PR to disable the auth check, but I imagine you want to fix this the right way.

**Comment by colemickens** [comment] 2019-12-09 08:31
It seems that the `firefox/wrapper.nix` has changed in `nixpkgs`, making another change to this repo necessary. I have a fork under my username here that one can find (and theoretically use in place of mozilla's fork temporarily). **It is insecure by nature, since it disables the signature verification check that this issue is about** (and thus is why I'm not sending a PR and am just leaving this comment).

**Closed** 2020-01-09 14:56 UTC
