### ISSUE TITLE
rust-overlay: nightly 2017-05-19 tries to write to /etc

### ISSUE THREAD

**Issue by Ralith** [mozilla/nixpkgs-mozilla#37] opened 2017-05-20 03:04 UTC
The build fails with `mkdir: cannot create directory '/etc/bash_completion.d': Permission denied`

**Comment by steveeJ** [comment] 2017-05-26 11:57
We have two options here:
* remove them from the source before installing
* install them to `$out/share/bash-completion/completions`

**Comment by zimbatm** [comment] 2017-05-26 15:05
(2) is the right answer. Upstream should be fixed to respect the destdir on install. They will want to support that on normal Linuxes as well.

**Comment by nbp** [comment] 2017-05-29 09:57
This issue seem to be coming from https://github.com/rust-lang/rust-installer/pull/59
I guess the problem seems to be that --prefix is not considered for the default value of --sysconfigdir, in the mean time I guess we could provided it as argument of the install script.

**Comment by nbp** [comment] 2017-05-29 09:59
And is a duplicate of https://github.com/rust-lang/rust/issues/42102 fixed by https://github.com/rust-lang/rust/pull/42124

**Closed by nbp** 2017-05-29 09:59 UTC
