### ISSUE TITLE
stdenv.lib is depreciated!

### ISSUE THREAD

**Issue by enderger** [mozilla/nixpkgs-mozilla#260] opened 2021-06-17 21:24 UTC
Hey,

Just wanted to quickly point out that currently this does not build on the current `nixos-unstable-small` branch, due to the use of `stdenv.lib` in several locations. This has been depreciated for quite some time, and no longer exists in the latest builds (if it's not already in `unstable`, it will be soon). It should be fairly trivial to fix, given that the lib input has already seen use alongside it's depreciated alias.

**Comment by baloo** [comment] 2021-06-18 19:41
duplicate of #250

**Comment by andersk** [comment] 2021-08-15 21:35
This was fixed in #250.

**Closed** 2021-08-17 05:11 UTC
